# Conda environment specification. The dependencies defined in this file will be
# automatically provisioned for runs against docker, VM, and HDI cluster targets.

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For Spark packages and configuration, see spark_dependencies.yml.

name: project_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5.2
  - scikit-learn
  - nltk
  - pandas
  - azure
  - gensim
  - scipy
  - wordcloud
  - azure-storage
  - pip:
    - notebook
    - matplotlib
    # The API for Azure Machine Learning Model Management Service.
    # Details: https://github.com/Azure/Machine-Learning-Operationalization
    - azure-ml-api-sdk==0.1.0a10

    # Library for collecting data from operationalized models
    - azureml.datacollector==0.1.0a13